site_name: Fold
repo_url: https://github.com/dream-faster/fold
repo_name: GitHub
site_author: Dream Faster
copyright: Dream Faster 2023
theme:
  name: material

nav:
    - Home: 'index.md'
    - Concepts:
      - Continuous Validation: 'continuous-validation.md'
      - Design: 'design.md'
      - Models: 'models.md'
      - Splitters: 'splitters.md'
    - Getting started:
      - Quick Start: 'quickstart.md'
      - Deployment: 'deployment.md'
    - 'reference.md'

plugins:
  - search
  - include-markdown
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            separate_signature: true
            show_submodules: true
            show_signature_annotations: true
          import:
          - https://docs.python-requests.org/en/master/objects.inv