site_name: Fold
repo_url: https://github.com/dream-faster/fold
repo_name: GitHub
site_author: Dream Faster
copyright: Dream Faster 2023
theme:
  name: material
  logo: images/logo_white.svg
  favicon: images/logo.svg
  features:
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: amber
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: amber
      accent: deep orange

nav:
    - Home: 'index.md'
    - Concepts:
      - Time Series Cross Validation: 'cross-validation.md'
      - Design: 'design.md'
      - Models: 'models.md'
      - Splitters: 'splitters.md'
    - Examples:
      - Date-time and Holiday features: 'examples/date'
      - Ensembling models: 'examples/ensembling'
      - Preprocess your data: 'examples/preprocess'
      - Tabular ML models: 'examples/tabular'
      - Transform your target variable: 'examples/transform-target'
    - 'reference.md'

plugins:
  - search
  - include-markdown
  - autorefs
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            separate_signature: true
            show_submodules: true
            show_signature_annotations: true
          import:
          - https://docs.python-requests.org/en/master/objects.inv