site_name: Fold
repo_url: https://github.com/dream-faster/fold
repo_name: GitHub
site_author: Dream Faster
copyright: Dream Faster 2023
theme:
  name: material

nav:
    - Home: 'index.md'
    - Concepts:
      - Time Series Cross Validation: 'cross-validation.md'
      - Design: 'design.md'
      - Models: 'models.md'
      - Splitters: 'splitters.md'
    - Examples:
      # - Simple ARIMA model: 'examples/arima'
      - Date-time and Holiday features: 'examples/date'
      - Ensembling models: 'examples/ensembling'
      - Preprocess your data: 'examples/preprocess'
      # - Stacking models: 'examples/stacking'
      - Tabular ML models: 'examples/tabular'
      - Transform your target variable: 'examples/transform-target'
    - 'reference.md'

plugins:
  - search
  - include-markdown
  - autorefs
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            separate_signature: true
            show_submodules: true
            show_signature_annotations: true
          import:
          - https://docs.python-requests.org/en/master/objects.inv