name: ci-cd


on:
  workflow_dispatch:
  push:
  release:
    types:
      - published

jobs:

  run-tests:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"

      - name: run-tests
        run: pytest . -s --cov --durations 0
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

  publish-package:
    needs: run-tests
    if: github.event_name == 'release'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: build-package
        run: hatch build

      - name: publish-package
        run: hatch publish --user __token__ --auth $PYPI_TOKEN
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
