name: tests


on:
  push:

jobs:

  unit-tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"

      - name: run-tests
        run: pytest tests/unit -s --cov --durations 0

      - uses: codecov/codecov-action@v3


  integration-tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"
          pip install ".[extras]"

      - name: run-tests
        run: pytest tests/integration -s --durations 0



  doc-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[tests]"
          pip install ".[extras]"

      - name: run-tests
        run: pytest src/ -s --durations 0
